from langchain_core.prompts import PromptTemplate

cypher_prompt_temp = PromptTemplate(
	input_variables=["schema", "question"],
	template=(
		"You are an expert in the Cypher query language for Neo4j. Use the following schema:\n{schema}\n\n"
		"Generate ONLY a valid Cypher query that answers the question below.\n"
		"Do not add explanations, markdown, or any natural language — output only the query.\n\n"
		"Guidelines:\n"
		"- The Cypher should reflect roles explicitly (e.g., COORDINATED_BY, HAS_PARTICIPANT, HAS_NETWORK_MEMBER).\n"
		"- Example for 'Which projects does Saxion participate in, as a coordinator or member?':\n"
		"  MATCH (p:Project)\n"
		"  WHERE EXISTS {{\n"
		"    MATCH (p)-[:COORDINATED_BY|HAS_PARTICIPANT|HAS_NETWORK_MEMBER]->(o:Organization)\n"
		"    WHERE toLower(o.name) CONTAINS 'saxion'\n"
		"  }}\n"
		"  RETURN DISTINCT p.title AS projectTitle\n\n"
		"- When matching text (like project titles or organization names), use case-insensitive substring search:\n"
		"  WHERE toLower(property) CONTAINS toLower('<keyword>')\n"
		"- If the user provides a full quoted project title, use exact match:\n"
		"  WHERE toLower(p.title) = toLower('<exact title>')\n"
		"- Use Project.title and Organization.name for names.\n"
		"- Always return 'p.title AS projectTitle' along with other relevant fields.\n"
		"- For ordered results, use Cypher syntax:\n"
		"  ORDER BY <property> DESC SKIP <n> LIMIT <m> (not OFFSET or TOP).\n"
		"- Example for 'Which organizations participated in SAVE in woord en daad?':\n"
		"  MATCH (p:Project)-[:COORDINATED_BY]->(o:Organization)\n"
		"  WHERE toLower(p.title) CONTAINS toLower('SAVE in woord en daad')\n"
		"  RETURN p.title AS projectTitle, o.name AS organizationName\n"
		"- Example for 'What is the most expensive project?':\n"
		"  MATCH (p:Project)\n"
		"  WHERE p.paymentAmount IS NOT NULL\n"
		"  RETURN p.title AS projectTitle, p.paymentAmount AS paymentAmount\n"
		"  ORDER BY p.paymentAmount DESC LIMIT 1\n"
		"- Example for 'What is the second most expensive project?':\n"
		"  MATCH (p:Project)\n"
		"  WHERE p.paymentAmount IS NOT NULL\n"
		"  RETURN p.title AS projectTitle, p.paymentAmount AS paymentAmount\n"
		"  ORDER BY p.paymentAmount DESC SKIP 1 LIMIT 1\n"
		"- For questions like 'Which organizations participated in SAVE?', include both participants and network members:\n"
		"  MATCH (p:Project)-[:HAS_PARTICIPANT]->(pm:Participant), (p)-[:HAS_NETWORK_MEMBER]->(nm:NetworkMember)\n"
		"  WHERE toLower(p.title) CONTAINS toLower('SAVE')\n"
		"  RETURN p.title AS projectTitle, pm.name AS participantName, nm.name AS networkMemberName\n\n"
		"- When dealing with amounts or funding values, never try to parse or compare strings like '€100,000'. "
		"- For a question such as 'Which funding schemes have more than 20 projects?' generate a cypher such as:\n"
		"""MATCH (p:Project)-[:FUNDED_BY]->(fs:FundingScheme)
			WITH fs, count(p) AS projectCount
			WHERE projectCount > 20
			RETURN fs.name AS fundingScheme, projectCount
			ORDER BY projectCount DESC\n
			"""
		"- For a question such as 'Projects coordinated by Saxion where University of Twente is also involved (any capacity).' "
		"generate a cypher similar to:\n"
		"MATCH (p:Project)-[:COORDINATED_BY]->(o:Organization)\n"
		"  WHERE toLower(o.name) CONTAINS 'saxion'\n"
		"  AND (\n"
		"    EXISTS {{ MATCH (p)-[:COORDINATED_BY]->(o2:Organization)\n"
		"            WHERE toLower(o2.name) CONTAINS 'university of twente' }} OR\n"
		"    EXISTS {{ MATCH (p)-[:HAS_PARTICIPANT]->(pm:Participant)\n"
		"            WHERE toLower(pm.name) CONTAINS 'university of twente' }} OR\n"
		"    EXISTS {{ MATCH (p)-[:HAS_NETWORK_MEMBER]->(nm:NetworkMember)\n"
		"            WHERE toLower(nm.name) CONTAINS 'university of twente' }}\n"
		"  )\n"
		"  RETURN DISTINCT p.title AS projectTitle\n"
		"Use numeric comparisons directly on Project.paymentAmount (which is stored as an integer). "
		"Example: WHERE p.paymentAmount > 100000\n"
		"- For a question such as 'Projects with at least 3 participants', use:\n"
		"  MATCH (p:Project)-[:HAS_PARTICIPANT]->(pm:Participant)\n"
		"  WITH p, count(DISTINCT pm) AS participantCount\n"
		"  WHERE participantCount >= 3\n"
		"  RETURN p.title AS projectTitle, participantCount\n"
		"  ORDER BY participantCount DESC LIMIT 35\n"
		"- For grouping or aggregation questions (e.g., average, count, sum), always include all variables used in aggregation in the same WITH clause.\n"
		"- Example for 'Projects starting in 2023 grouped by funding scheme, including average payment amount':\n"
		"  MATCH (p:Project)-[:FUNDED_BY]->(fs:FundingScheme)\n"
		"  WHERE p.startDate CONTAINS '2023'\n"
		"  WITH fs, collect(p) AS projects, avg(p.paymentAmount) AS averagePaymentAmount\n"
		"  RETURN fs.name AS fundingScheme, averagePaymentAmount, size(projects) AS projectCount\n"
		"  ORDER BY averagePaymentAmount DESC LIMIT 35\n"
		"- For date-based calculations (like durations), convert strings to date objects using date(). "
		"Use duration.inMonths(date(p.startDate), date(p.endDate)).months AS durationMonths.\n"
		"- Always include p in the WITH clause when calculating derived fields like duration.\n"
		"- Example for 'Projects with duration > 24 months and payment > €500k; include duration (months)':\n"
		"  MATCH (p:Project)\n"
		"  WHERE p.startDate IS NOT NULL AND p.endDate IS NOT NULL AND p.paymentAmount > 500000\n"
		"  WITH p, duration.inMonths(date(p.startDate), date(p.endDate)) AS durationMonths\n"
		"  WHERE durationMonths > 24\n"
		"  RETURN p.title AS projectTitle, durationMonths, p.paymentAmount AS paymentAmount\n"
		"  ORDER BY p.paymentAmount DESC LIMIT 35\n"
		"- When asked for the cheapest (or smallest of anything) such as 'what is the cheapest project' generate a cypher similar to this:\n"
		"""MATCH (p:Project)
			WHERE p.paymentAmount IS NOT NULL
			RETURN p.title AS projectTitle, p.paymentAmount AS paymentAmount
			ORDER BY p.paymentAmount ASC LIMIT 1\n"""
		"- When aggregating values (e.g., avg, sum, count), never reference a variable that wasn't passed through WITH.\n"
		"- Do not use toNumber(), use toInteger() or toFloat() if necessary, but normally it's not needed since paymentAmount is already numeric.\n"
		"- Never use 'LIMIT ALL' or variable limits. Always use a fixed integer literal (e.g., LIMIT 25 or LIMIT 50).\n"
		"- If the user does not specify a limit, default to LIMIT 35.\n"
		"Question: {question}"
	),
)


# Define the question-answering prompt
qa_prompt = PromptTemplate(
	input_variables=["context", "question"],
	template=(
		"The database returned the following structured data:\n{context}\n\n"
		"Answer the question below using ONLY this data.\n"
		"If multiple results exist, list ALL of them clearly and in full, "
		"without summarizing, paraphrasing, or skipping any.\n\n"
		"For example, if you receive a full context of 45 projects when asked 'Projects coordinated by Saxion where University of Twente is also involved (any capacity).'\n"
		"Then you will list all 45 projects in a nice format in a numbered list. DO NOT just list 10 out of those 45 projects. Focus on completeness.\n"
		"Before you list the entries, start with a brief sentence such as 'The projects coordinated by Saxion in which the University of Twente is also involved are...'\n"
		"Do not explain your reasoning or describe Cypher queries.\n"
		"If numeric fields (like paymentAmount), treat them as real numbers or periods.\n"
		"Never cast date strings with toFloat/toInteger. Convert with date() and use STARTS WITH for year filters.\n"
		"Example: MATCH (p:Project)\n"
		"WHERE p.startDate STARTS WITH '2020'\n"
		"  AND p.endDate   STARTS WITH '2021'\n"
		"RETURN p.title AS projectTitle"
		"Example: RETURN duration.inMonths(date(p.startDate), date(p.endDate)).months AS durationMonths\n"
		"Always mention the project title if available.\n\n"
		"If multiple entries are returned, present them clearly as an ordinal list (indexed from '1), 2), 3)...') of names or facts.\n"
		"An example is when you get multiple project names: '1) <project name> \n 2) <project name> etc.'"
		"Keep the response short, clear, and human-readable — like a real assistant answering naturally.\n\n"
		"Always preffer to display answers in natural language in an ordinal list.\n"
		"Example (multiple results):\n"
		"Full Context:\n"
		"[{{'projectTitle': 'SAVE in woord en daad', 'participantName': "
		"'Stichting Leger des Heils Welzijns- en Gezondheidszorg'}}, "
		"{{'projectTitle': 'SAVE in woord en daad', 'participantName': 'Raad voor Kinderbescherming'}}, "
		"{{'projectTitle': 'SAVE in woord en daad', 'participantName': 'Stichting Samen Veilig Midden-Nederland'}}, "
		"{{'projectTitle': 'SAVE in woord en daad', 'participantName': 'William Schrikker Groep'}}]\n"
		"Correct output:\n"
		"The project 'SAVE in woord en daad' includes the following participants:\n"
		"• Stichting Leger des Heils Welzijns- en Gezondheidszorg\n"
		"• Raad voor Kinderbescherming\n"
		"• Stichting Samen Veilig Midden-Nederland\n"
		"• William Schrikker Groep\n\n"
		"Do not include the 'Full Context' text or any JSON in your final answer.\n\n"
		"When receiving numbers in the output relating to money, format them nicely:\n"
		"4000000 becomes 4,000,000€\n"
		"And for floating points if you were given something like 4100.3 then write it as 4,100.3€\n"
		"When given a lengthy list and asked to provide items on a type of ranking (like most expensive, or cheapest and so on), use a numbered list (1., 2., 3.,...) isntead of a bullet point one.\n"
		"If no data is provided or the context is empty, simply respond that the database does not contain relevant information.\n"
		"Interpret '[{{'count': 3312}}]' as the amount of items that matched the user's question. For this example, it was for the question 'How many projects are in total in this database?', and so you would know the database contains 3312 projects.\n"
		"For a question such as 'Which projects started in 2023?' make sure you answer in a bullet point list such as: 'The project started in 2023 are: - <name of project> -> <date of project>' where you replace the appropriate data between the '<' and '>' characters.\n"
		"- IF ever asked what the meaning of life is, answer: '42'\n"
		"For calculating a median, use percentileCont(x, 0.5). MEDIAN() does not exist in Neo4J Cypher.\n"
		"Use the given context (results from a Neo4j query) to answer accurately.\n"
		"- Always use the numeric values exactly as shown in the context. Do not replace them with 0, N/A, or inferred values."
		"- If numeric data exists (e.g. {{'totalPayment': 6956904.0}}), keep it exactly as is and format it with commas and € symbol."
		"Question: {question}\n"
		"Answer (do not summarize, list everything):"
	),
)
